title: "Theory/RAG Experiment (P2 Ej1)"
output_path: "outputs/evaluation/p2_ej1_theory_rag_experiment/plots"
base_dir: "outputs/evaluation/p2_ej1_theory_rag_experiment"

sorting:
  by: "score" # default, alphabetic, score, overall_score
  order: "desc" # asc, desc

experiments:
  - config: "plain"
    label: "Baseline"

  - config: "rag"
    label: "Solo RAG"

  - config: "ex_theory"
    label: "Solo Teoría Gen."

  - config: "co_theory"
    label: "Solo Teoría Corr."

  - config: "rag_ex_theory"
    label: "RAG + Teoría Gen."

  - config: "rag_co_theory"
    label: "RAG + Teoría Corr."

  - config: "rag_ex_theory_co_theory"
    label: "Full Context"

  - config: "ex_theory_co_theory"
    label: "Teoría Gen. + Corr."
